LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE:= SAM4E_Firmware.elf
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := SAM4E_Firmware.elf
LOCAL_MODULE_TAGS := optional
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MODULE_OWNER := qti
LOCAL_MODULE_PATH := $(TARGET_OUT_ETC)/firmware
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE:= RH850_Firmware.out
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := RH850_Firmware.out
LOCAL_MODULE_TAGS := optional
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MODULE_OWNER := qti
LOCAL_MODULE_PATH := $(TARGET_OUT_ETC)/firmware
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE:= rh850_fw.out
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := rh850_fw.out
LOCAL_MODULE_TAGS := optional
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MODULE_OWNER := qti
LOCAL_MODULE_PATH := $(TARGET_OUT_ETC)/firmware
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE:= rh850_fw.hex
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := rh850_fw.hex
LOCAL_MODULE_TAGS := optional
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MODULE_OWNER := qti
LOCAL_MODULE_PATH := $(TARGET_OUT_ETC)/firmware
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE:= rh850_boot_fw.out
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := rh850_boot_fw.out
LOCAL_MODULE_TAGS := optional
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MODULE_OWNER := qti
LOCAL_MODULE_PATH := $(TARGET_OUT_ETC)/firmware
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE:= rh850_boot_fw.hex
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := rh850_boot_fw.hex
LOCAL_MODULE_TAGS := optional
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MODULE_OWNER := qti
LOCAL_MODULE_PATH := $(TARGET_OUT_ETC)/firmware
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE:= rh850_upgrade_fw.out
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := rh850_upgrade_fw.out
LOCAL_MODULE_TAGS := optional
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MODULE_OWNER := qti
LOCAL_MODULE_PATH := $(TARGET_OUT_ETC)/firmware
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE:= rh850_upgrade_fw.hex
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := rh850_upgrade_fw.hex
LOCAL_MODULE_TAGS := optional
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MODULE_OWNER := qti
LOCAL_MODULE_PATH := $(TARGET_OUT_ETC)/firmware
include $(BUILD_PREBUILT)

