#! /bin/sh
#
# Copyright (c) 2016-2017 Qualcomm Technologies, Inc.
# All Rights Reserved.
# Confidential and Proprietary - Qualcomm Technologies, Inc.
#
# rilmuxd - init.d script to start the rilmuxd daemon service
#

set -e

case "$1" in
  start)
        # Create folders
        echo -n "Starting rilmuxd: "
        start-stop-daemon -S -b -a /usr/bin/rilmuxd
        echo "done"
        ;;
  stop)
        echo -n "Stopping rilmuxd: "
        start-stop-daemon -K -n rilmuxd
        echo "done"
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage $0 { start | stop | restart}" >&2
        exit 1
        ;;
esac

exit 0

