#! /bin/sh
#
#Copyright (c) 2017 Qualcomm Technologies, Inc.
#All Rights Reserved.
#Confidential and Proprietary - Qualcomm Technologies, Inc.
#
# port_bridge   init.d script to start the Data Software's port_bridge daemon

set -e

case "$1" in
  start)
        echo -n "Starting port_bridge: " > /dev/kmsg
        start-stop-daemon -S -b -a /usr/bin/port_bridge
        echo "done" > /dev/kmsg
        ;;
  stop)
        echo -n "Stopping port_bridge: " > /dev/kmsg
        start-stop-daemon -K -n port_bridge
        echo "done" > /dev/kmsg
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage port_bridge { start | stop | restart}" >&2
        exit 1
        ;;
esac

exit 0

