# location proprietary packages
require ../common-location-prop-image.inc

IMAGE_INSTALL += "loc-mcm-test-shim"
IMAGE_INSTALL += "loc-mcm-qmi-test-shim"
IMAGE_INSTALL += "loc-mcm-type-conv"
IMAGE_INSTALL += "loc-hal-test-shim"
IMAGE_INSTALL += "location-hal-tests"
IMAGE_INSTALL += "dr-ap-service"
IMAGE_INSTALL += "slim-daemon"
IMAGE_INSTALL += "izat-client-api"
IMAGE_INSTALL += "lowi-server"
IMAGE_INSTALL += "lowi-test"
IMAGE_INSTALL += "xtwifi-client"
IMAGE_INSTALL += "xtwifi-inet-agent"
IMAGE_INSTALL += "gtp-ap-le-os-agent"
IMAGE_INSTALL += "mcmlocserver"